### ISSUE TITLE
Warning in opam uninstall

### ISSUE THREAD

**Issue by fblanqui** [rlepigre/lambdapi#57]
12:17 ~/src/deducteam/lambdapi-lsp-git opam uninstall lambdapi
The following actions will be performed:
  ⊘  remove lambdapi dev

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[WARNING] Directory /local/blanqui/.opam/4.07.0/lib/lambdapi is not empty, not
          removing
⊘  removed   lambdapi.dev
Done.

Does make uninstall remove the library files too?

**Comment by rlepigre** [comment]
Yes it does remove everything. You probably have an old version installed, removing the folder by hand should solve the problem once and for all.

**Comment by fblanqui** [comment]
No: I removed every thing and still get this warning:

14:09 ~/lambdapi-git \rm -rf /local/blanqui/.opam/4.07.0/lib/lambdapi/
14:09 ~/lambdapi-git opam install lambdapi-lsp
The following actions will be performed:
   ∗  install lambdapi     dev                 [required by lambdapi-lsp]
   ∗  install lambdapi-lsp dev
===== ∗  2 =====
Do you want to continue ? [Y/n] Y

=-=- Gathering sources 
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[lambdapi-lsp] https://github.com/Deducteam/lambdapi-lsp.git updated
[lambdapi] https://github.com/rlepigre/lambdapi.git updated

=-=- Processing actions 
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed lambdapi.dev
∗  installed lambdapi-lsp.dev
Done.
14:10 ~/lambdapi-git opam uninstall lambdapi
The following actions will be performed:
   ⊘  remove lambdapi-lsp dev                  [uses lambdapi]
   ⊘  remove lambdapi     dev
===== ⊘  2 =====
Do you want to continue ? [Y/n] Y

=-=- Processing actions 
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
⊘  removed   lambdapi-lsp.dev
[WARNING] Directory /local/blanqui/.opam/4.07.0/lib/lambdapi is not 
empty, not
           removing
⊘  removed   lambdapi.dev
Done.


Le 26/07/2018 à 13:18, Rodolphe Lepigre a écrit :

**Comment by rlepigre** [comment]
Well, I don't see how this relate to `lambdapi`. If anything, this is an `opam` problem. Both `make install` and `make uninstall` behave as expected in the `lambdapi` repository.

**Comment by rlepigre** [comment]
However, it seems to me that `lambdapi-lsp` does not have an `uninstall` target. Shouldn't it have one?

**Comment by fblanqui** [comment]
Yes. You could add some lambdapi-lsp.opam file also if you want.


Le 26/07/2018 à 17:05, Rodolphe Lepigre a écrit :
