### ISSUE TITLE
Provide equality for AST

### ISSUE THREAD

**Issue by ejgallego** [rlepigre/lambdapi#88]
#86 needs to compare input AST in order to be able to perform incremental checking.

Unfortunately, the choice of an imperative representation for `Pos.pos` means that polymorphic equality won't work on `Syntax.p_cmd`. There are many approaches to fix this, any of them would work for us as long as we get a working equality operator for the AST.

**Comment by rlepigre** [comment]
OK, I'm soon going to change the `Pos.pos` soon, so I'll handle that.

**Comment by ejgallego** [comment]
Thanks @rlepigre !

**Comment by ejgallego** [comment]
I think that was the only problem to compare AST, but it would be good to add a unit test indeed.

**Comment by rlepigre** [comment]
You can now use polymorphic equality on positions!

**Comment by ejgallego** [comment]
I'm afraid that won't work due to the `Lazy.t` wrapper.

Note that current `master` is also broken due to new hacks is parse, concretely: `let parse_file = Pervasives.ref (fun _ -> assert false)`

**Comment by ejgallego** [comment]
Example:
```
$ dune utop src
  File "src/core.cma(Env)", line 1:
  Warning 31: files src/core.cma(Env) and /home/egallego/.opam/4.07.0/lib/ocaml/compiler-libs/ocamlcommon.cma(Env) both define a module named Env
  File "src/core.cma(Parser)", line 1:
  Warning 31: files src/core.cma(Parser) and /home/egallego/.opam/4.07.0/lib/ocaml/compiler-libs/ocamlcommon.cma(Parser) both define a module named Parser
  File "/home/egallego/.opam/4.07.0/lib/toplevel/topfind", line 1:
  Error: The files _build/default/src/.utop/utop.exe
       and /home/egallego/.opam/4.07.0/lib/ocaml/compiler-libs/toploop.cmi
       make inconsistent assumptions over interface Env

utop # let s = List.hd Pure.(parse_text "symbol const B : Type");;
val s : Pure.command Pos.loc = {Pos.elt = <abstr>; pos = Some <lazy>}
utop # s = s;;
Exception: Invalid_argument "compare: functional value".
```

Note, I strongly suggest you set `(wrapped true)` in the core library
or else rename the `Env` module. This will become a hard error in
future OCaml versions.

**Comment by ejgallego** [comment]
Anyways polymorphic equality won't work well once tactics or elaboration start to become more complex [as they will need equality for sure].

**Comment by rlepigre** [comment]
The bug should be fixed by eb153fa867a608729252fb0a6bb3f15effe02055. Note that the hacks will disappear soon, I'm working on parsing right now.

As for the `lazy` thing, I don't see what it should not work. Is there any profound reason you believe so?

**Comment by rlepigre** [comment]
Actually, you are right. I'll implement proper comparison function.

**Comment by ejgallego** [comment]
> As for the `lazy` thing, I don't see what it should not work. Is there any profound reason you believe so?

The polymorphic equality doesn't understand the closure when the lazy value hasn't been forced.

**Comment by rlepigre** [comment]
That's what I thought, and I actually only tested with values... Not with suspended computations.

Anyway, things should be fixed with ae7e75de1f8064f41423381a6556dcdbf8547572.

**Comment by ejgallego** [comment]
Sorry @rlepigre if I was not clear, what I need here is a function:
```ocaml
eq : Pure.command -> Pure.command -> bool
```
such that:
```ocaml
let s = Pure.parse_text "symbol const B : TYPE" in eq s s;;
```
returns true. Right now, if I make `eq = (=)` that still doesn't work.

I could go an implement such function manually, or use a preprocessor to do so, and even in that case there are a few choices, so that's why I'm opening the issue to discuss.

**Comment by rlepigre** [comment]
OK, I see. Do you expect the function to return `true` on two identical commands which have different positions?

**Comment by ejgallego** [comment]
> OK, I see. Do you expect the function to return `true` on two identical commands which have different positions?

For this particular use case I think we don't care.
